import {
  siReact,
  siNextdotjs,
  siTypescript,
  siTailwindcss,
  siFramer,
  siHtml5,
  siCss,
  siJavascript,
  siSass,
  siJquery,
  siNodedotjs,
  siExpress,
  siSupabase,
  siPostgresql,
  siMysql,
  siSanity,
  siN8n,
  siPostman,
  siGit,
  siGithub,
  siVercel,
  siFigma,
  siAnthropic,
  siResend,
  siVite,
  siAppwrite,
  siStripe,
} from 'simple-icons'
import type { SimpleIcon } from 'simple-icons'

export const SKILL_ICONS: Record<string, SimpleIcon> = {
  react: siReact,
  nextjs: siNextdotjs,
  typescript: siTypescript,
  tailwindcss: siTailwindcss,
  framer: siFramer,
  html5: siHtml5,
  css: siCss,
  sass: siSass,
  javascript: siJavascript,
  jquery: siJquery,
  nodejs: siNodedotjs,
  express: siExpress,
  supabase: siSupabase,
  postgresql: siPostgresql,
  mysql: siMysql,
  sanity: siSanity,
  n8n: siN8n,
  postman: siPostman,
  git: siGit,
  github: siGithub,
  vercel: siVercel,
  figma: siFigma,
  anthropic: siAnthropic,
  resend: siResend,
  vite: siVite,
  appwrite: siAppwrite,
  stripe: siStripe,
}

export const TECH_LABEL_TO_KEY: Record<string, string> = {
  'React': 'react',
  'Next.js': 'nextjs',
  'TypeScript': 'typescript',
  'Tailwind CSS': 'tailwindcss',
  'Framer Motion': 'framer',
  'HTML5': 'html5',
  'CSS': 'css',
  'SCSS': 'sass',
  'JavaScript': 'javascript',
  'jQuery': 'jquery',
  'Node.js': 'nodejs',
  'Express.js': 'express',
  'Supabase': 'supabase',
  'PostgreSQL': 'postgresql',
  'MySQL': 'mysql',
  'Sanity': 'sanity',
  'n8n': 'n8n',
  'Postman': 'postman',
  'Git': 'git',
  'GitHub': 'github',
  'Vercel': 'vercel',
  'Figma': 'figma',
  'Vite': 'vite',
  'Appwrite': 'appwrite',
  'Stripe': 'stripe',
}
